### ISSUE TITLE
Fix CTP6 tests 

### ISSUE THREAD

**Issue by ErikEJ** [DotNetAnalyzers/TSqlAnalyzer#15]
Need to get new test helpers from updated sdk templates

**Comment by sharwell** [comment]
I recommend you take the ones from StyleCopAnalyzers. Aside from working in CTP 6, the two major additional items are:

1. Uses xunit instead of MSTest as the underlying framework
2. Properly uses `async`/`await` instead of making synchronous calls to asynchronous methods

**Comment by sharwell** [comment]
BTW, I've done this conversion for other projects before. Let me know if you'd like me to do the above and send a pull request.

**Comment by ErikEJ** [comment]
Sounds great, a PR would be most welcome. It is this test class that needs to run Again: https://github.com/DotNetAnalyzers/TSqlAnalyzer/blob/master/src/TSqlAnalyzer/TSqlAnalyzer/TSqlAnalyzer.Test/UnitTests.cs
